[workspace]
resolver = "3"
members = [
  # examples
  "examples",
  "moat",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
repository = "https://github.com/mrcroxx/moat"
homepage = "https://github.com/mrcroxx/moat"
keywords = ["cache", "hybrid"]
authors = ["MrCroxx <mrcroxx.cs@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.87"
