networks:
  dev:
    driver: bridge
  
volumes:
  minio:

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    networks:
      - dev
  init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    networks:
      - dev
    entrypoint: >
      sh -c "
      sleep 2;
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb minio/dev;
      "
 
  s3proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: moat:latest
    networks:
      - dev
    ports:
      - "23456:23456"
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    command:
      - ./moat
      - --endpoint
      - http://minio:9000
      - --access-key-id
      - minioadmin
      - --secret-access-key
      - minioadmin
      - --region
      - us-east-1
      - --host
      - 0.0.0.0


