# Copyright 2025 Moat Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

networks:
  dev:
    driver: bridge
  
volumes:
  minio:

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    networks:
      - dev
  init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    networks:
      - dev
    entrypoint: >
      sh -c "
      sleep 2;
      mc alias set minio http://minio:9000 minioadmin minioadmin;
      mc mb minio/dev;
      "
 
  moat:
    build:
      context: .
      dockerfile: Dockerfile
    image: moat:latest
    networks:
      - dev
    ports:
      - "23456:23456"
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    command:
      - --listen
      - 0.0.0.0:23456
      - --s3-endpoint
      - http://minio:9000
      - --s3-access-key-id
      - minioadmin
      - --s3-secret-access-key
      - minioadmin
      - --s3-region
      - us-east-1


