apiVersion: v1
kind: Service
metadata:
  name: {{ include "moat.fullname" . }}
  labels:
    {{- include "moat.labels" . | nindent 4 }}
spec:
  clusterIP: None
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moat.selectorLabels" . | nindent 4 }}
