# Copyright 2026- Moat Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "moat-cache-disk-compare"
version = "0.0.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[workspace]

[dependencies]
anyhow = "1"
foyer = { git = "https://github.com/foyer-rs/foyer.git", rev = "dd46245c45071d1036331e4e2c48e15386017b96" }
futures-util = "0.3"
hdrhistogram = "7"
libc = "0.2"
moat-cache = { path = "../../core/moat-cache" }
moat-common = { path = "../../core/moat-common" }
moat-engine = { path = "../../core/moat-engine" }
moat-engine-v2 = { path = "../../core/moat-engine-v2" }
moat-server = { path = "../../core/moat-server" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "time",
  "sync",
  "macros",
] }

[profile.release]
debug = 1
