# Copyright 2025 Moat Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  scrape_interval: 1s
  evaluation_interval: "5s"

storage:
  tsdb:
    out_of_order_time_window: 30m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

# https://prometheus.io/docs/guides/opentelemetry/#promoting-resource-attributes
# otlp:
#   promote_resource_attributes:
#     - service.instance.id
#     - service.name
#     - service.namespace
#     - cloud.availability_zone
#     - cloud.region
#     - container.name
#     - deployment.environment.name
#     - k8s.cluster.name
#     - k8s.container.name
#     - k8s.cronjob.name
#     - k8s.daemonset.name
#     - k8s.deployment.name
#     - k8s.job.name
#     - k8s.namespace.name
#     - k8s.pod.name
#     - k8s.replicaset.name
#     - k8s.statefulset.name
