name: "CI"

on:
  push:
    branches:
      - "main"
      - "forks/*"
      - release-*.*
  pull_request:
    branches:
      - "main"
      - "v*.*.*-rc"
      - release-*.*

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}


env:
    CARGO_TERM_COLOR: always
    CACHE_KEY_SUFFIX: 20250610

jobs:
  