{
 "title": "moat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "S3 Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(moat_s3_count_total[$__rate_interval])) by (peer, operation, extra, status)",
     "legendFormat": "{{peer}} - {{operation}} - {{extra}} - {{status}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(moat_s3_bytes_total[$__rate_interval])) by (peer, operation, extra, status)",
     "legendFormat": "{{peer}} - {{operation}} - {{extra}} - {{status}}"
    }
   ]
  },
  { "title": "Member View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Members (moat-1)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "moat_peer_up{peer=\"moat-cache-1:23456\"} >= 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Members (moat-2)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "moat_peer_up{peer=\"moat-cache-2:23457\"} >= 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Members (moat-3)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "moat_peer_up{peer=\"moat-cache-3:23458\"} >= 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Members (moat-4)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "moat_peer_up{peer=\"moat-cache-4:23459\"} >= 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Log View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logs (moat-1)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"moat\"} | label_format level=detected_level | peer = `moat-cache-1:23456`"
    }
   ]
  },
  {
   "title": "Logs (moat-2)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"moat\"} | label_format level=detected_level | peer = `moat-cache-2:23457`"
    }
   ]
  },
  {
   "title": "Logs (moat-3)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"moat\"} | label_format level=detected_level | peer = `moat-cache-3:23458`"
    }
   ]
  },
  {
   "title": "Logs (moat-4)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"moat\"} | label_format level=detected_level | peer = `moat-cache-4:23459`"
    }
   ]
  }
 ]
}