# Copyright 2026- Moat Project Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI

on:
  push:
    branches:
      - main
      - release-*.*
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  check:
    name: fmt, clippy, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Spelling
        uses: crate-ci/typos@master
      - name: TOML formatting
        uses: uncenter/setup-taplo@v1
      - run: taplo fmt --check
      - name: Dependency ordering
        run: cargo install cargo-sort --locked && cargo sort --workspace --check
      - name: Unused dependencies
        uses: bnjbvr/cargo-machete@main
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets
      - name: Test
        run: cargo test --workspace
      - name: Docs
        run: cargo doc --workspace --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
